FROM python:3.11-slim

WORKDIR /app

# Копирование requirements и установнка зависимостей
COPY frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода frontend
COPY frontend/ .

# Запуск Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]